blank_issues_enabled: true
contact_links:
  - name: Self-serve Request
    url: https://github.com/ipfs-shipyard/github-mgmt/edit/master/github/ipfs-shipyard.yml
    about: Propose a GitHub configuration change by modifying ipfs-shipyard.yml
