blank_issues_enabled: true
contact_links:
  - name: PR
    url: https://github.com/ipfs-shipyard/github-mgmt/edit/master/github/ipfs-shipyard.yml
    about: Propose GitHub configuration change by modifying ipfs-shipyard.yml
